name: Executes integration tests
on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.5'
      - name: Execute tests
        run: |
          sudo apt update
          sudo apt install -y make rsyslog
          sudo cp rsyslog/config/rsyslog-2.conf /etc/rsyslog.conf
          sudo mkdir -p /var/log/audito-maldito
          sudo mkdir -p /app-audit
          sudo mkfifo /app-audit/app-events-output-test.log
          sudo mkfifo /var/log/audito-maldito/sshd-pipe
          sudo mkfifo /var/log/audito-maldito/audit-pipe
          sudo systemctl restart rsyslog
          sudo make integration-test
          
